chore: added script for local build
catenax-ng/catenax-at-home pull request #21
Opened 2022-04-21 10:12 UTC by domreuter

This script will build the different projects and start up the containers

2022-04-21 12:53 UTC, florianrusch-zf commented
Hi @domreuter thanks for you PR! Sadly the steps in the build file are not complete. Before you can run this, you need to build the EDC modules and to publish it into your local maven cache.

For the moment we added the IntelliJ Run Configs into the repository, so everybody can use them independently from their operation systems. If we want to add such a script, we should ensure, that it runs on all operating systems as well.

Additionally we plan to create a better `README.md` to provide a better onboarding (Take a look at #25).

Therefore it would be awesome, if you can ensure, that your script runs at least on Windows, Linux and Mac.

2022-04-21 13:08 UTC, florianrusch-zf requested changes

2022-04-21 13:08 UTC, florianrusch-zf commented on api-wrapper/build_run_local.sh
> +docker-compose --file docker-compose.yml --project-name catenax_at_home --verbose up
- The `--file` flag is not needed.
- The `--verbose` flat also.
- Setting the `--project-name` flag is a great idea! But I would then set in the `docker-compose.yml` files directly. Can you do that?

```suggestion
docker-compose build
docker-compose up
```

2022-04-21 13:08 UTC, florianrusch-zf commented on api-wrapper/build_run_local.sh
> +export MAVEN_OPTS=(${GRADLE_PROPS[*]})
Do we really need this?

2022-04-21 17:30 UTC, domreuter commented on api-wrapper/build_run_local.sh
> +chmod +x gradlew
Had some problems with one of the gradle wrappers, it was not marked as executable per default. Need to figure out which one exactly it was

2022-04-21 17:37 UTC, domreuter commented on api-wrapper/build_run_local.sh
> +docker-compose --file docker-compose.yml --project-name catenax_at_home --verbose up
The `--file` is there for some other reasons. I will work with multiple compose files, therefore i need this one. By now only the default compose-file is referenced here.

I will integrate the project-name in the docker-compose for a better overview of the container naming.

2022-04-25 12:57 UTC, domreuter commented on api-wrapper/build_run_local.sh
> +export DOCKER_PLATFORM=${DOCKER_PLATFORM:-linux/amd64}
fixed this!

2022-04-25 12:58 UTC, domreuter commented on api-wrapper/build_run_local.sh
> +export MAVEN_OPTS=(${GRADLE_PROPS[*]})
fixed: no need for this anymore!

2022-04-26 06:36 UTC, florianrusch-zf requested changes

2022-04-26 06:36 UTC, florianrusch-zf commented on api-wrapper/docker-compose-consumer.yml
> +      - "5014:8090" # debugging
Missing empty line at EOF
```suggestion
      - "5014:8090" # debugging

```

2022-04-26 06:36 UTC, florianrusch-zf commented on api-wrapper/docker-compose-provider.yml
> +      - "5010:8090" # debugging
Missing empty line at EOF

```suggestion
      - "5010:8090" # debugging

```

2022-04-26 06:36 UTC, florianrusch-zf commented on api-wrapper/build_run_local.sh
> +#docker-compose --file docker-compose.yml --project-name catenax_at_home --verbose up
Missing empty line at EOF
```suggestion
#docker-compose --file docker-compose.yml --project-name catenax_at_home --verbose up

```

2022-04-26 06:36 UTC, florianrusch-zf commented on api-wrapper/build_run_local.sh
> +./gradlew clean build
If we skip the tests in the steps 1 & 2, we should do it in all other steps also
```suggestion
./gradlew clean build -x test
```

2022-04-26 06:36 UTC, florianrusch-zf commented on api-wrapper/build_run_local.sh
> +./gradlew clean build
```suggestion
./gradlew clean build -x test
```

2022-04-26 06:36 UTC, florianrusch-zf commented on api-wrapper/build_run_local.sh
> +./gradlew clean build
```suggestion
./gradlew clean build -x test
```

2022-04-26 06:36 UTC, florianrusch-zf commented on api-wrapper/build_run_local.sh
> +./gradlew ${MAVEN_OPTS} clean build
I think we don't need the `MAVEN_OPTS` anymore or?

```suggestion
./gradlew clean build -x test
```

2022-04-26 06:36 UTC, florianrusch-zf commented on api-wrapper/build_run_local.sh
> +docker-compose --file docker-compose-centralservices.yml --project-name centralservices_catenax_at_home up &
Didn't we discussed last time that we want to move the `project-name` into the `docker-compose.yml` files?

2022-04-26 06:36 UTC, florianrusch-zf commented on api-wrapper/build_run_local.sh
> +  echo "Folder ${DIR} already exists: Deleting ${DIR}"
```suggestion
  echo "Folder ${DIR} already exists: Deleting ${DIR}"
  rm -rf $DIR
```

2022-04-26 07:19 UTC, domreuter commented on api-wrapper/build_run_local.sh
> +mvn clean install -DskipTests
fixed: uses internal mvn wrapper now

2022-04-26 07:38 UTC, domreuter commented on api-wrapper/build_run_local.sh
> +docker-compose --file docker-compose-centralservices.yml --project-name centralservices_catenax_at_home up &
If you found an easy way to do so feel free to add this one, atm it is only possible via environment variables.

2022-04-28 06:53 UTC, florianrusch-zf commented on api-wrapper/build_run_local.sh
> +docker-compose --file docker-compose-centralservices.yml --project-name centralservices_catenax_at_home up &
With the newest Compose-Version its possible 😉  But I'm not sure if we should enforce all the users to upgrade to the latest version 🤔

2022-04-28 07:01 UTC, florianrusch-zf requested changes

2022-04-28 07:01 UTC, florianrusch-zf commented on api-wrapper/docker-compose-provider.yml
> +      - "8492:9192" # public (/public)
```suggestion
      - "8492:9192" # public (/public)
```

2022-04-28 14:48 UTC, domreuter commented on api-wrapper/build_run_local.sh
> +docker-compose --file docker-compose-centralservices.yml --project-name centralservices_catenax_at_home up &
any sources about that?

2024-06-13 14:36 UTC, closed without merging