Implement and Test FileSystemVault in ApiWrapper
catenax-ng/catenax-at-home pull request #86
Opened 2022-05-19 08:05 UTC by diegogomez-zf

2022-05-30 05:32 UTC, florianrusch-zf requested changes

2022-05-30 05:32 UTC, florianrusch-zf commented on api-wrapper/services/api-wrapper/src/main/java/net/catenax/edc/apiwrapper/security/BasicAuthenticationService.java
> +        return this.listAuthVault.stream().filter(isCorrectUser).filter(isCorrectVaultKey).findAny().isPresent();
```suggestion
        return listAuthVault.stream()
                .filter(isCorrectUser)
                .filter(isCorrectVaultKey)
                .findAny()
                .isPresent();
```

2022-05-30 05:32 UTC, florianrusch-zf commented on api-wrapper/services/api-wrapper/src/test/java/net/catenax/edc/apiwrapper/config/ApiWrapperConfigTest.java
> +        credentialsList.add(credentials);
Avoid logic, where it's not necessary ;-)

```suggestion
        List<BasicAuthVaultLabels> credentialsList = List.of(
                new BasicAuthVaultLabels("UserId", "UserPwd")
        );
```

2022-05-30 05:32 UTC, florianrusch-zf commented on api-wrapper/services/api-wrapper/vault.properties
> +wraper-auth-basic-usera=password
Please remove this file

2022-05-30 05:32 UTC, florianrusch-zf commented on api-wrapper/services/api-wrapper/configurations.properties
> +wrapper.auth.basic.usera=wraper-auth-basic-usera
Please remove this file and add a little bit of documentation in the `api-wrapper/README.md`. I think you can mostly copy & paste from here: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/extensions/api/auth-basic#usageexample

2022-05-30 09:58 UTC, diegogomez-zf commented on api-wrapper/services/api-wrapper/src/main/java/net/catenax/edc/apiwrapper/ApiWrapperExtension.java
> +                .collect(Collectors.toList());
I replaced your suggestion config (line 93) with entryConfig because config is already defined in the scope (Config class)

2022-05-30 12:46 UTC, florianrusch-zf requested changes

2022-05-30 12:46 UTC, florianrusch-zf commented on api-wrapper/services/api-wrapper/src/README.md
> +# Basic authentication
Move `Basic authentication` to the second level:
```suggestion
# API-Wrapper

## Basic authentication
```

2022-05-30 12:46 UTC, florianrusch-zf commented on api-wrapper/services/api-wrapper/src/README.md
> +## Usage/Example
```suggestion
### Usage/Example
```

2022-05-30 12:46 UTC, florianrusch-zf commented on api-wrapper/services/api-wrapper/src/README.md
> +if you provide at least one credential pair.
Please rewrite this part. This is not an extension which provides an `AuthenticationService` implementation 🤣

2022-05-30 12:46 UTC, florianrusch-zf commented on api-wrapper/services/api-wrapper/src/README.md
> +Regarding the keys you have to provide in your EDC configuration the vault key for each user:
```suggestion
In your EDC configuration you must then specify the respective vault key for the respective user:
```

2022-05-30 12:46 UTC, florianrusch-zf commented on api-wrapper/services/api-wrapper/src/README.md
> +```
```suggestion
```

2022-05-30 12:46 UTC, florianrusch-zf commented on api-wrapper/services/api-wrapper/src/test/java/net/catenax/edc/apiwrapper/config/ApiWrapperConfigTest.java
> +        List<BasicAuthVaultLabels> credentialsList = List.of(new BasicAuthVaultLabels("UserId","UserPwd"));
```suggestion
        List<BasicAuthVaultLabels> credentialsList = List.of(new BasicAuthVaultLabels("UserId", "UserPwd"));
```

2022-05-31 05:51 UTC, florianrusch-zf requested changes

2022-05-31 05:51 UTC, florianrusch-zf commented on api-wrapper/services/api-wrapper/src/README.md
> +In your EDC configuration you must then specify the respective vault key for the respective user:
```suggestion

In your EDC configuration you must then specify the respective vault key for the respective user:
```

2022-05-31 05:51 UTC, florianrusch-zf commented on api-wrapper/services/api-wrapper/src/test/java/net/catenax/edc/apiwrapper/security/BasicAuthenticationServiceTest.java
> +        Map<String, List<String>> mapCorrectPassword = Map.of("user", new ArrayList<>(Arrays.asList("user dXNlcjpwYXNzd29yZA==", "blablabla")));
You can do this also on the other functions
```suggestion
        Map<String, List<String>> mapCorrectPassword = Map.of("user", List.of("user dXNlcjpwYXNzd29yZA==", "blablabla")));
```

2022-05-31 05:51 UTC, florianrusch-zf commented on api-wrapper/services/api-wrapper/src/main/java/net/catenax/edc/apiwrapper/security/BasicAuthenticationService.java
> +        Predicate<BasicAuthVaultLabels> isCorrectVaultKey = e -> vault.resolveSecret(e.getVaultKey()).equals(password);
`vault.resolveSecret()` is nullable, therefor we shouldn't call a function on it
```suggestion
        Predicate<BasicAuthVaultLabels> isCorrectVaultKey = e -> Objects.equals(vault.resolveSecret(e.getVaultKey()), password)
```

2022-05-31 05:51 UTC, florianrusch-zf commented on api-wrapper/services/api-wrapper/src/main/java/net/catenax/edc/apiwrapper/security/BasicAuthenticationService.java
> +                .isPresent();
IntelliJ says, that this is shorter 😅

```suggestion
                .anyMatch(isCorrectVaultKey);
```

2022-05-31 05:51 UTC, florianrusch-zf commented on api-wrapper/services/api-wrapper/src/test/java/net/catenax/edc/apiwrapper/security/BasicAuthenticationServiceTest.java
> +        Result<BasicAuthenticationService.BasicAuthCredentials> result = Whitebox.invokeMethod(authenticationServiceTest,"decodeAuthHeader","userdXNlcjpwYXNzd29yZA");
You don't like to set spaces or? 😅
Think it's easier if you just run reformat in intellij for this on the whole file.

```suggestion
        Result<BasicAuthenticationService.BasicAuthCredentials> result = Whitebox.invokeMethod(authenticationServiceTest, "decodeAuthHeader", "userdXNlcjpwYXNzd29yZA");
```

2022-05-31 05:51 UTC, florianrusch-zf commented on api-wrapper/services/api-wrapper/src/test/java/net/catenax/edc/apiwrapper/security/BasicAuthenticationServiceTest.java
> +        assertThat(result.getFailureMessages().get(0)).isEqualTo("Authorization header could not be base64 decoded");
to be honest, I'm not sure if these tests are really useful/correct. E.g. if we change the messages, we also have to change the tests. But we'll just leave them there for now – better than no tests! 😉 👍

2022-05-31 05:51 UTC, florianrusch-zf commented on api-wrapper/services/api-wrapper/build.gradle.kts
> +    testImplementation("org.powermock:powermock-api-mockito:1.6.2")
Could you please update all the test dependencies?

```
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.8.2")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.8.2")
    testImplementation("org.assertj:assertj-core:3.22.0")
    testImplementation("org.mockito:mockito-inline:4.5.1")
    testImplementation("org.powermock:powermock-api-mockito:1.7.4")
```

2022-05-31 05:51 UTC, florianrusch-zf commented on api-wrapper/services/api-wrapper/build.gradle.kts
Can you please add this to this file? This allows us to simply run `./gradlew test`
```
tasks.test {
    useJUnitPlatform()
}
```

2022-05-31 10:35 UTC, florianrusch-zf approved these changes

2022-05-31 10:38 UTC, florianrusch-zf requested changes
Test it with azure key vault

2022-10-18 10:24 UTC, closed without merging